# fly.toml app configuration file generated for simscore-api-dev on 2024-12-17T15:48:00+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simscore-api-dev'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
